//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./web_types');
//HELPER FUNCTIONS AND STRUCTURES

DataServer_execute_args = function(args) {
  this.model = null;
  this.item = null;
  this.inputStr = null;
  if (args) {
    if (args.model !== undefined && args.model !== null) {
      this.model = args.model;
    }
    if (args.item !== undefined && args.item !== null) {
      this.item = args.item;
    }
    if (args.inputStr !== undefined && args.inputStr !== null) {
      this.inputStr = args.inputStr;
    }
  }
};
DataServer_execute_args.prototype = {};
DataServer_execute_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.model = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.item = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.inputStr = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DataServer_execute_args.prototype.write = function(output) {
  output.writeStructBegin('DataServer_execute_args');
  if (this.model !== null && this.model !== undefined) {
    output.writeFieldBegin('model', Thrift.Type.STRING, 1);
    output.writeString(this.model);
    output.writeFieldEnd();
  }
  if (this.item !== null && this.item !== undefined) {
    output.writeFieldBegin('item', Thrift.Type.STRING, 2);
    output.writeString(this.item);
    output.writeFieldEnd();
  }
  if (this.inputStr !== null && this.inputStr !== undefined) {
    output.writeFieldBegin('inputStr', Thrift.Type.STRING, 3);
    output.writeString(this.inputStr);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

DataServer_execute_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
DataServer_execute_result.prototype = {};
DataServer_execute_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DataServer_execute_result.prototype.write = function(output) {
  output.writeStructBegin('DataServer_execute_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

DataServerClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
DataServerClient.prototype = {};
DataServerClient.prototype.seqid = function() { return this._seqid; }
DataServerClient.prototype.new_seqid = function() { return this._seqid += 1; }
DataServerClient.prototype.execute = function(model, item, inputStr, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_execute(model, item, inputStr);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_execute(model, item, inputStr);
  }
};

DataServerClient.prototype.send_execute = function(model, item, inputStr) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('execute', Thrift.MessageType.CALL, this.seqid());
  var args = new DataServer_execute_args();
  args.model = model;
  args.item = item;
  args.inputStr = inputStr;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

DataServerClient.prototype.recv_execute = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new DataServer_execute_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('execute failed: unknown result');
};
DataServerProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
DataServerProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

DataServerProcessor.prototype.process_execute = function(seqid, input, output) {
  var args = new DataServer_execute_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.execute.length === 3) {
    Q.fcall(this._handler.execute, args.model, args.item, args.inputStr)
      .then(function(result) {
        var result = new DataServer_execute_result({success: result});
        output.writeMessageBegin("execute", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("execute", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.execute(args.model, args.item, args.inputStr, function (err, result) {
      if (err == null) {
        var result = new DataServer_execute_result((err != null ? err : {success: result}));
        output.writeMessageBegin("execute", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("execute", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

